# Generated by Django 4.1.1 on 2022-10-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeScreenModel',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=32)),
                ('label_anchor', models.CharField(max_length=32)),
                ('label_active', models.BooleanField(default=False)),
                ('label_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceScreenModel',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=64)),
                ('source_key', models.CharField(max_length=64)),
                ('source_thumbnail', models.CharField(max_length=244)),
                ('source_date', models.DateTimeField(auto_now_add=True)),
                ('source_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.homescreenmodel')),
            ],
        ),
    ]
