# Generated by Django 4.1.1 on 2022-10-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcescreenmodel',
            name='source_thumbnail',
            field=models.URLField(max_length=244),
        ),
    ]
