# Generated by Django 4.1.1 on 2022-10-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sourcescreenmodel_source_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcescreenmodel',
            name='source_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_screen', to='api.homescreenmodel'),
        ),
    ]
