# Generated by Django 4.1.1 on 2022-09-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackModel',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('radio_name', models.CharField(max_length=50)),
                ('track_source', models.CharField(max_length=50)),
                ('track_singer', models.CharField(max_length=50)),
                ('track_name', models.CharField(max_length=50)),
                ('track_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_song_artists', models.TextField(null=True)),
                ('spotify_song_id', models.CharField(max_length=50)),
                ('spotify_song_api', models.CharField(max_length=400)),
                ('spotify_song_external_urls', models.CharField(max_length=400)),
                ('spotify_song_preview', models.CharField(max_length=400)),
                ('spotify_song_thumbnail', models.CharField(max_length=400)),
                ('spotify_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('spotify_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.trackmodel')),
            ],
        ),
    ]
