# Generated by Django 4.1.1 on 2022-09-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifymodel',
            name='updated_date',
        ),
    ]
