# Generated by Django 4.1.1 on 2022-09-27 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_remove_spotifymodel_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifymodel',
            name='updated_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
