# Generated by Django 4.1.1 on 2022-09-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_spotifymodel_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifymodel',
            name='spotify_song_preview',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
