# Generated by Django 4.1.1 on 2022-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_alter_spotifymodel_spotify_song_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifymodel',
            name='spotify_date',
            field=models.DateField(auto_now=True),
        ),
    ]
