# Generated by Django 4.1.1 on 2022-10-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0005_alter_spotifymodel_spotify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifymodel',
            name='updated_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
