# Generated by Django 4.1.1 on 2022-10-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0006_alter_spotifymodel_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifymodel',
            name='spotify_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='spotifymodel',
            name='updated_date',
            field=models.DateField(),
        ),
    ]
