# Generated by Django 4.1.1 on 2022-10-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0007_alter_spotifymodel_spotify_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifymodel',
            name='spotify_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spotifymodel',
            name='spotify_song_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='spotifymodel',
            name='updated_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
