# Generated by Django 4.1.1 on 2022-10-09 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0009_alter_spotifymodel_spotify_song_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodel',
            name='track_date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='track_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
