# Generated by Django 4.1.1 on 2022-10-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0010_trackmodel_track_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='radio_name',
            field=models.CharField(max_length=244),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='track_name',
            field=models.CharField(max_length=244),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='track_singer',
            field=models.CharField(max_length=244),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='track_source',
            field=models.CharField(max_length=244),
        ),
    ]
