# Generated by Django 4.1.1 on 2022-10-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0011_alter_trackmodel_radio_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='track_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
