# Generated by Django 4.1.1 on 2022-10-16 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0012_alter_trackmodel_track_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='track_date_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 15, 10, 51, 864999)),
        ),
    ]
